// Generated by CoffeeScript 2.7.0
var AttachedCache, IP, U2, Url, escapeSlash, exports, shExp2RegExp,
  hasProp = {}.hasOwnProperty;

U2 = require('uglify-js');

IP = require('ip-address');

Url = require('url');

({shExp2RegExp, escapeSlash} = require('./shexp_utils'));

({AttachedCache} = require('./utils'));

module.exports = exports = {
  requestFromUrl: function(url) {
    var req;
    if (typeof url === 'string') {
      url = Url.parse(url);
    }
    return req = {
      url: Url.format(url),
      host: url.hostname,
      scheme: url.protocol.replace(':', '')
    };
  },
  urlWildcard2HostWildcard: function(pattern) {
    var result;
    result = pattern.match(/^\*:\/\/((?:\w|[?*._\-])+)\/\*$/); // Begins with *://
    // The host part follows.
    // And ends with /*
    return result != null ? result[1] : void 0;
  },
  tag: function(condition) {
    return exports._condCache.tag(condition);
  },
  analyze: function(condition) {
    return exports._condCache.get(condition, function() {
      return {
        analyzed: exports._handler(condition.conditionType).analyze.call(exports, condition)
      };
    });
  },
  match: function(condition, request) {
    var cache;
    cache = exports.analyze(condition);
    return exports._handler(condition.conditionType).match.call(exports, condition, request, cache);
  },
  compile: function(condition) {
    var cache, handler;
    cache = exports.analyze(condition);
    if (cache.compiled) {
      return cache.compiled;
    }
    handler = exports._handler(condition.conditionType);
    return cache.compiled = handler.compile.call(exports, condition, cache);
  },
  str: function(condition, {abbr} = {
      abbr: -1
    }) {
    var endCode, handler, part, result, str, typeStr;
    handler = exports._handler(condition.conditionType);
    if (handler.abbrs[0].length === 0) {
      endCode = condition.pattern.charCodeAt(condition.pattern.length - 1);
      if (endCode !== exports.colonCharCode && condition.pattern.indexOf(' ') < 0) {
        return condition.pattern;
      }
    }
    str = handler.str;
    typeStr = typeof abbr === 'number' ? handler.abbrs[(handler.abbrs.length + abbr) % handler.abbrs.length] : condition.conditionType;
    result = typeStr + ':';
    part = str ? str.call(exports, condition) : condition.pattern;
    if (part) {
      result += ' ' + part;
    }
    return result;
  },
  colonCharCode: ':'.charCodeAt(0),
  fromStr: function(str) {
    var condition, conditionType, fromStr, i;
    str = str.trim();
    i = str.indexOf(' ');
    if (i < 0) {
      i = str.length;
    }
    if (str.charCodeAt(i - 1) === exports.colonCharCode) {
      conditionType = str.substr(0, i - 1);
      str = str.substr(i + 1).trim();
    } else {
      conditionType = '';
    }
    conditionType = exports.typeFromAbbr(conditionType);
    if (!conditionType) {
      return null;
    }
    condition = {
      conditionType: conditionType
    };
    fromStr = exports._handler(condition.conditionType).fromStr;
    if (fromStr) {
      return fromStr.call(exports, str, condition);
    } else {
      condition.pattern = str;
      return condition;
    }
  },
  _abbrs: null,
  typeFromAbbr: function(abbr) {
    var ab, abbrs, j, len, ref, type;
    if (!exports._abbrs) {
      exports._abbrs = {};
      ref = exports._conditionTypes;
      for (type in ref) {
        if (!hasProp.call(ref, type)) continue;
        ({abbrs} = ref[type]);
        exports._abbrs[type.toUpperCase()] = type;
        for (j = 0, len = abbrs.length; j < len; j++) {
          ab = abbrs[j];
          exports._abbrs[ab.toUpperCase()] = type;
        }
      }
    }
    return exports._abbrs[abbr.toUpperCase()];
  },
  comment: function(comment, node) {
    var base;
    if (!comment) {
      return node;
    }
    if (node.start == null) {
      node.start = {};
    }
    // This hack is needed to allow dumping comments in repeated print call.
    Object.defineProperty(node.start, '_comments_dumped', {
      get: function() {
        return false;
      },
      set: function() {
        return false;
      }
    });
    if ((base = node.start).comments_before == null) {
      base.comments_before = [];
    }
    node.start.comments_before.push({
      type: 'comment2',
      value: comment
    });
    return node;
  },
  safeRegex: function(expr) {
    var _;
    try {
      return new RegExp(expr);
    } catch (error) {
      _ = error;
      // Invalid regexp! Fall back to a regexp that does not match anything.
      return /(?!)/;
    }
  },
  regTest: function(expr, regexp) {
    if (typeof regexp === 'string') {
      // Escape (unescaped) forward slash for use in regex literals.
      regexp = regexSafe(escapeSlash(regexp));
    }
    if (typeof expr === 'string') {
      expr = new U2.AST_SymbolRef({
        name: expr
      });
    }
    return new U2.AST_Call({
      args: [expr],
      expression: new U2.AST_Dot({
        property: 'test',
        expression: new U2.AST_RegExp({
          value: regexp
        })
      })
    });
  },
  isInt: function(num) {
    return typeof num === 'number' && !isNaN(num) && parseFloat(num) === parseInt(num, 10);
  },
  between: function(val, min, max, comment) {
    var pos, str, tmpl;
    if (min === max) {
      if (typeof min === 'number') {
        min = new U2.AST_Number({
          value: min
        });
      }
      return exports.comment(comment, new U2.AST_Binary({
        left: val,
        operator: '===',
        right: min
      }));
    }
    if (min > max) {
      return exports.comment(comment, new U2.AST_False());
    }
    if (exports.isInt(min) && exports.isInt(max) && max - min < 32) {
      comment || (comment = `${min} <= value && value <= ${max}`);
      tmpl = "0123456789abcdefghijklmnopqrstuvwxyz";
      str = max < tmpl.length ? tmpl.substr(min, max - min + 1) : tmpl.substr(0, max - min + 1);
      pos = min === 0 ? val : new U2.AST_Binary({
        left: val,
        operator: '-',
        right: new U2.AST_Number({
          value: min
        })
      });
      return exports.comment(comment, new U2.AST_Binary({
        left: new U2.AST_Call({
          expression: new U2.AST_Dot({
            expression: new U2.AST_String({
              value: str
            }),
            property: 'charCodeAt'
          }),
          args: [pos]
        }),
        operator: '>',
        right: new U2.AST_Number({
          value: 0
        })
      }));
    }
    if (typeof min === 'number') {
      min = new U2.AST_Number({
        value: min
      });
    }
    if (typeof max === 'number') {
      max = new U2.AST_Number({
        value: max
      });
    }
    return exports.comment(comment, new U2.AST_Call({
      args: [val, min, max],
      expression: new U2.AST_Function({
        argnames: [
          new U2.AST_SymbolFunarg({
            name: 'value'
          }),
          new U2.AST_SymbolFunarg({
            name: 'min'
          }),
          new U2.AST_SymbolFunarg({
            name: 'max'
          })
        ],
        body: [
          new U2.AST_Return({
            value: new U2.AST_Binary({
              left: new U2.AST_Binary({
                left: new U2.AST_SymbolRef({
                  name: 'min'
                }),
                operator: '<=',
                right: new U2.AST_SymbolRef({
                  name: 'value'
                })
              }),
              operator: '&&',
              right: new U2.AST_Binary({
                left: new U2.AST_SymbolRef({
                  name: 'value'
                }),
                operator: '<=',
                right: new U2.AST_SymbolRef({
                  name: 'max'
                })
              })
            })
          })
        ]
      })
    }));
  },
  parseIp: function(ip) {
    var addr;
    if (ip.charCodeAt(0) === '['.charCodeAt(0)) {
      ip = ip.substr(1, ip.length - 2);
    }
    addr = new IP.v4.Address(ip);
    if (!addr.isValid()) {
      addr = new IP.v6.Address(ip);
      if (!addr.isValid()) {
        return null;
      }
    }
    return addr;
  },
  normalizeIp: function(addr) {
    var ref;
    return ((ref = addr.correctForm) != null ? ref : addr.canonicalForm).call(addr);
  },
  ipv6Max: new IP.v6.Address('::/0').endAddress().canonicalForm(),
  localHosts: ["127.0.0.1", "[::1]", "localhost"],
  getWeekdayList: function(condition) {
    var i, j, k, results, results1;
    if (condition.days) {
      results = [];
      for (i = j = 0; j < 7; i = ++j) {
        results.push(condition.days.charCodeAt(i) > 64);
      }
      return results;
    } else {
      results1 = [];
      for (i = k = 0; k < 7; i = ++k) {
        results1.push((condition.startDay <= i && i <= condition.endDay));
      }
      return results1;
    }
  },
  _condCache: new AttachedCache(function(condition) {
    var result, tag;
    tag = exports._handler(condition.conditionType).tag;
    result = tag ? tag.apply(exports, arguments) : exports.str(condition);
    return condition.conditionType + '$' + result;
  }),
  _setProp: function(obj, prop, value) {
    if (!Object.prototype.hasOwnProperty.call(obj, prop)) {
      Object.defineProperty(obj, prop, {
        writable: true
      });
    }
    return obj[prop] = value;
  },
  _handler: function(conditionType) {
    var handler;
    if (typeof conditionType !== 'string') {
      conditionType = conditionType.conditionType;
    }
    handler = exports._conditionTypes[conditionType];
    if (handler == null) {
      throw new Error(`Unknown condition type: ${conditionType}`);
    }
    return handler;
  },
  _conditionTypes: {
    // These functions are .call()-ed with `this` set to module.exports.
    // coffeelint: disable=missing_fat_arrows
    'TrueCondition': {
      abbrs: ['True'],
      analyze: function(condition) {
        return null;
      },
      match: function() {
        return true;
      },
      compile: function(condition) {
        return new U2.AST_True();
      },
      str: function(condition) {
        return '';
      },
      fromStr: function(str, condition) {
        return condition;
      }
    },
    'FalseCondition': {
      abbrs: ['False', 'Disabled'],
      analyze: function(condition) {
        return null;
      },
      match: function() {
        return false;
      },
      compile: function(condition) {
        return new U2.AST_False();
      },
      fromStr: function(str, condition) {
        if (str.length > 0) {
          condition.pattern = str;
        }
        return condition;
      }
    },
    'UrlRegexCondition': {
      abbrs: ['UR', 'URegex', 'UrlR', 'UrlRegex'],
      analyze: function(condition) {
        return this.safeRegex(escapeSlash(condition.pattern));
      },
      match: function(condition, request, cache) {
        return cache.analyzed.test(request.url);
      },
      compile: function(condition, cache) {
        return this.regTest('url', cache.analyzed);
      }
    },
    'UrlWildcardCondition': {
      abbrs: ['U', 'UW', 'Url', 'UrlW', 'UWild', 'UWildcard', 'UrlWild', 'UrlWildcard'],
      analyze: function(condition) {
        var parts, pattern;
        parts = (function() {
          var j, len, ref, results;
          ref = condition.pattern.split('|');
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            pattern = ref[j];
            if (pattern) {
              results.push(shExp2RegExp(pattern, {
                trimAsterisk: true
              }));
            }
          }
          return results;
        })();
        return this.safeRegex(parts.join('|'));
      },
      match: function(condition, request, cache) {
        return cache.analyzed.test(request.url);
      },
      compile: function(condition, cache) {
        return this.regTest('url', cache.analyzed);
      }
    },
    'HostRegexCondition': {
      abbrs: ['R', 'HR', 'Regex', 'HostR', 'HRegex', 'HostRegex'],
      analyze: function(condition) {
        return this.safeRegex(escapeSlash(condition.pattern));
      },
      match: function(condition, request, cache) {
        return cache.analyzed.test(request.host);
      },
      compile: function(condition, cache) {
        return this.regTest('host', cache.analyzed);
      }
    },
    'HostWildcardCondition': {
      abbrs: ['', 'H', 'W', 'HW', 'Wild', 'Wildcard', 'Host', 'HostW', 'HWild', 'HWildcard', 'HostWild', 'HostWildcard'],
      analyze: function(condition) {
        var parts, pattern;
        parts = (function() {
          var j, len, ref, results;
          ref = condition.pattern.split('|');
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            pattern = ref[j];
            if (!(pattern)) {
              continue;
            }
            // Get the magical regex of this pattern. See
            // https://github.com/FelisCatus/SwitchyOmega/wiki/Host-wildcard-condition
            // for the magic.
            if (pattern.charCodeAt(0) === '.'.charCodeAt(0)) {
              pattern = '*' + pattern;
            }
            if (pattern.indexOf('**.') === 0) {
              results.push(shExp2RegExp(pattern.substring(1), {
                trimAsterisk: true
              }));
            } else if (pattern.indexOf('*.') === 0) {
              results.push(shExp2RegExp(pattern.substring(2), {
                trimAsterisk: false
              }).replace(/./, '(?:^|\\.)').replace(/\.\*\$$/, ''));
            } else {
              results.push(shExp2RegExp(pattern, {
                trimAsterisk: true
              }));
            }
          }
          return results;
        })();
        return this.safeRegex(parts.join('|'));
      },
      match: function(condition, request, cache) {
        return cache.analyzed.test(request.host);
      },
      compile: function(condition, cache) {
        return this.regTest('host', cache.analyzed);
      }
    },
    'BypassCondition': {
      abbrs: ['B', 'Bypass'],
      analyze: function(condition) {
        var addr, cache, matchPort, parts, pos, prefixLen, ref, scheme, server, serverIp, serverRegex;
        // See https://developer.chrome.com/extensions/proxy#bypass_list
        cache = {
          host: null,
          ip: null,
          scheme: null,
          url: null,
          normalizedPattern: ''
        };
        server = condition.pattern;
        if (server === '<local>') {
          cache.host = server;
          return cache;
        }
        parts = server.split('://');
        if (parts.length > 1) {
          cache.scheme = parts[0];
          cache.normalizedPattern = cache.scheme + '://';
          server = parts[1];
        }
        parts = server.split('/');
        if (parts.length > 1) {
          addr = this.parseIp(parts[0]);
          prefixLen = parseInt(parts[1]);
          if (addr && !isNaN(prefixLen)) {
            cache.ip = {
              conditionType: 'IpCondition',
              ip: this.normalizeIp(addr),
              prefixLength: prefixLen
            };
            cache.normalizedPattern += cache.ip.ip + '/' + cache.ip.prefixLength;
            return cache;
          }
        }
        // The server can be an IP address with or without brackets.
        serverIp = this.parseIp(server);
        if (serverIp == null) {
          pos = server.lastIndexOf(':');
          if (pos >= 0) {
            matchPort = server.substring(pos + 1);
            server = server.substring(0, pos);
          }
          serverIp = this.parseIp(server);
        }
        if (serverIp != null) {
          server = this.normalizeIp(serverIp);
          if (serverIp.v4) {
            cache.normalizedPattern += server;
          } else {
            cache.normalizedPattern += '[' + server + ']';
          }
        } else {
          if (server.charCodeAt(0) === '.'.charCodeAt(0)) {
            server = '*' + server;
          }
          cache.normalizedPattern = server;
        }
        if (matchPort) {
          cache.port = matchPort;
          cache.normalizedPattern += ':' + cache.port;
          // In URL, IPv6 server addresses need to be bracketed.
          if ((serverIp != null) && !serverIp.v4) {
            server = '[' + server + ']';
          }
          serverRegex = shExp2RegExp(server);
          serverRegex = serverRegex.substring(1, serverRegex.length - 1);
          scheme = (ref = cache.scheme) != null ? ref : '[^:]+';
          cache.url = this.safeRegex('^' + scheme + ':\\/\\/' + serverRegex + ':' + matchPort + '\\/');
        } else if (server !== '*') {
          // In host, IPv6 server addresses are never bracketed.
          serverRegex = shExp2RegExp(server, {
            trimAsterisk: true
          });
          cache.host = this.safeRegex(serverRegex);
        }
        return cache;
      },
      match: function(condition, request, cache) {
        cache = cache.analyzed;
        if ((cache.scheme != null) && cache.scheme !== request.scheme) {
          return false;
        }
        if ((cache.ip != null) && !this.match(cache.ip, request)) {
          return false;
        }
        if (cache.host != null) {
          if (cache.host === '<local>') {
            // https://code.google.com/p/chromium/codesearch#chromium/src/net/proxy/proxy_bypass_rules.cc&sq=package:chromium&l=67
            // We align with Chromium's behavior of bypassing 127.0.0.1, ::1 as
            // well as any host without dots.

            // This, however, will match IPv6 literals who also don't have dots.
            return request.host === '127.0.0.1' || request.host === '::1' || request.host.indexOf('.') < 0;
          } else {
            if (!cache.host.test(request.host)) {
              return false;
            }
          }
        }
        if ((cache.url != null) && !cache.url.test(request.url)) {
          return false;
        }
        return true;
      },
      str: function(condition) {
        var analyze, cache;
        analyze = this._handler(condition).analyze;
        cache = analyze.call(exports, condition);
        if (cache.normalizedPattern) {
          return cache.normalizedPattern;
        } else {
          return condition.pattern;
        }
      },
      compile: function(condition, cache) {
        var conditions, hostEquals;
        cache = cache.analyzed;
        if (cache.url != null) {
          return this.regTest('url', cache.url);
        }
        conditions = [];
        if (cache.host === '<local>') {
          hostEquals = function(host) {
            return new U2.AST_Binary({
              left: new U2.AST_SymbolRef({
                name: 'host'
              }),
              operator: '===',
              right: new U2.AST_String({
                value: host
              })
            });
          };
          return new U2.AST_Binary({
            left: new U2.AST_Binary({
              left: hostEquals('127.0.0.1'),
              operator: '||',
              right: hostEquals('::1')
            }),
            operator: '||',
            right: new U2.AST_Binary({
              left: new U2.AST_Call({
                expression: new U2.AST_Dot({
                  expression: new U2.AST_SymbolRef({
                    name: 'host'
                  }),
                  property: 'indexOf'
                }),
                args: [
                  new U2.AST_String({
                    value: '.'
                  })
                ]
              }),
              operator: '<',
              right: new U2.AST_Number({
                value: 0
              })
            })
          });
        }
        if (cache.scheme != null) {
          conditions.push(new U2.AST_Binary({
            left: new U2.AST_SymbolRef({
              name: 'scheme'
            }),
            operator: '===',
            right: new U2.AST_String({
              value: cache.scheme
            })
          }));
        }
        if (cache.host != null) {
          conditions.push(this.regTest('host', cache.host));
        } else if (cache.ip != null) {
          conditions.push(this.compile(cache.ip));
        }
        switch (conditions.length) {
          case 0:
            return new U2.AST_True();
          case 1:
            return conditions[0];
          case 2:
            return new U2.AST_Binary({
              left: conditions[0],
              operator: '&&',
              right: conditions[1]
            });
        }
      }
    },
    'KeywordCondition': {
      abbrs: ['K', 'KW', 'Keyword'],
      analyze: function(condition) {
        return null;
      },
      match: function(condition, request) {
        return request.scheme === 'http' && request.url.indexOf(condition.pattern) >= 0;
      },
      compile: function(condition) {
        return new U2.AST_Binary({
          left: new U2.AST_Binary({
            left: new U2.AST_SymbolRef({
              name: 'scheme'
            }),
            operator: '===',
            right: new U2.AST_String({
              value: 'http'
            })
          }),
          operator: '&&',
          right: new U2.AST_Binary({
            left: new U2.AST_Call({
              expression: new U2.AST_Dot({
                expression: new U2.AST_SymbolRef({
                  name: 'url'
                }),
                property: 'indexOf'
              }),
              args: [
                new U2.AST_String({
                  value: condition.pattern
                })
              ]
            }),
            operator: '>=',
            right: new U2.AST_Number({
              value: 0
            })
          })
        });
      }
    },
    'IpCondition': {
      abbrs: ['Ip'],
      analyze: function(condition) {
        var addr, cache, ip, mask;
        cache = {
          addr: null,
          normalized: null
        };
        ip = condition.ip;
        if (ip.charCodeAt(0) === '['.charCodeAt(0)) {
          ip = ip.substr(1, ip.length - 2);
        }
        addr = ip + '/' + condition.prefixLength;
        cache.addr = this.parseIp(addr);
        if (cache.addr == null) {
          throw new Error(`Invalid IP address ${addr}`);
        }
        cache.normalized = this.normalizeIp(cache.addr);
        mask = cache.addr.v4 ? new IP.v4.Address('255.255.255.255/' + cache.addr.subnetMask) : new IP.v6.Address(this.ipv6Max + '/' + cache.addr.subnetMask);
        cache.mask = this.normalizeIp(mask.startAddress());
        return cache;
      },
      match: function(condition, request, cache) {
        var addr;
        addr = this.parseIp(request.host);
        if (addr == null) {
          return false;
        }
        cache = cache.analyzed;
        if (addr.v4 !== cache.addr.v4) {
          return false;
        }
        return addr.isInSubnet(cache.addr);
      },
      compile: function(condition, cache) {
        var hostIsInNet, hostIsInNetEx, hostLooksLikeIp;
        cache = cache.analyzed;
        // We want to make sure that host is not a domain name before we pass it
        // to isInNet. Otherwise an expensive dns lookup might be triggered.
        // For performance reasons, we just check the last character of host.
        // If it's a digit, we assume that host is valid IPv4 address.
        hostLooksLikeIp = cache.addr.v4 ? new U2.AST_Binary({
          left: new U2.AST_Sub({
            expression: new U2.AST_SymbolRef({
              name: 'host'
            }),
            property: new U2.AST_Binary({
              left: new U2.AST_Dot({
                expression: new U2.AST_SymbolRef({
                  name: 'host'
                }),
                property: 'length'
              }),
              operator: '-',
              right: new U2.AST_Number({
                value: 1
              })
            })
          }),
          operator: '>=',
          right: new U2.AST_Number({
            value: 0
          })
        // Likewise, we assume that host is valid IPv6 if it contains colons.
        }) : new U2.AST_Binary({
          left: new U2.AST_Call({
            expression: new U2.AST_Dot({
              expression: new U2.AST_SymbolRef({
                name: 'host'
              }),
              property: 'indexOf'
            }),
            args: [
              new U2.AST_String({
                value: ':'
              })
            ]
          }),
          operator: '>=',
          right: new U2.AST_Number({
            value: 0
          })
        });
        if (cache.addr.subnetMask === 0) {
          // 0.0.0.0/0 (matches all IPv4 literals), or ::/0 (all IPv6 literals).
          // Use hostLooksLikeIp instead of isInNet for better efficiency and
          // browser support.
          return hostLooksLikeIp;
        }
        hostIsInNet = new U2.AST_Call({
          expression: new U2.AST_SymbolRef({
            name: 'isInNet'
          }),
          args: [
            new U2.AST_SymbolRef({
              name: 'host'
            }),
            new U2.AST_String({
              value: cache.normalized
            }),
            new U2.AST_String({
              value: cache.mask
            })
          ]
        });
        if (!cache.addr.v4) {
          // Example: isInNetEx(host,"fefe:13::abc/33")
          // For documentation on the isInNetEx function, see:
          // https://msdn.microsoft.com/en-us/library/windows/desktop/gg308479(v=vs.85).aspx
          hostIsInNetEx = new U2.AST_Call({
            expression: new U2.AST_SymbolRef({
              name: 'isInNetEx'
            }),
            args: [
              new U2.AST_SymbolRef({
                name: 'host'
              }),
              new U2.AST_String({
                value: cache.normalized + cache.addr.subnet
              })
            ]
          });
          // Use isInNetEx if possible.
          hostIsInNet = new U2.AST_Conditional({
            condition: new U2.AST_Binary({
              left: new U2.AST_UnaryPrefix({
                operator: 'typeof',
                expression: new U2.AST_SymbolRef({
                  name: 'isInNetEx'
                })
              }),
              operator: '===',
              right: new U2.AST_String({
                value: 'function'
              })
            }),
            consequent: hostIsInNetEx,
            alternative: hostIsInNet
          });
        }
        return new U2.AST_Binary({
          left: hostLooksLikeIp,
          operator: '&&',
          right: hostIsInNet
        });
      },
      str: function(condition) {
        return condition.ip + '/' + condition.prefixLength;
      },
      fromStr: function(str, condition) {
        var addr;
        addr = this.parseIp(str);
        if (addr != null) {
          condition.ip = addr.addressMinusSuffix;
          condition.prefixLength = addr.subnetMask;
        } else {
          condition.ip = '0.0.0.0';
          condition.prefixLength = 0;
        }
        return condition;
      }
    },
    'HostLevelsCondition': {
      abbrs: ['Lv', 'Level', 'Levels', 'HL', 'HLv', 'HLevel', 'HLevels', 'HostL', 'HostLv', 'HostLevel', 'HostLevels'],
      analyze: function(condition) {
        return '.'.charCodeAt(0);
      },
      match: function(condition, request, cache) {
        var dotCharCode, dotCount, i, j, ref;
        dotCharCode = cache.analyzed;
        dotCount = 0;
        for (i = j = 0, ref = request.host.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
          if (request.host.charCodeAt(i) === dotCharCode) {
            dotCount++;
            if (dotCount > condition.maxValue) {
              return false;
            }
          }
        }
        return dotCount >= condition.minValue;
      },
      compile: function(condition) {
        var val;
        val = new U2.AST_Dot({
          property: 'length',
          expression: new U2.AST_Call({
            args: [
              new U2.AST_String({
                value: '.'
              })
            ],
            expression: new U2.AST_Dot({
              expression: new U2.AST_SymbolRef({
                name: 'host'
              }),
              property: 'split'
            })
          })
        });
        return this.between(val, condition.minValue + 1, condition.maxValue + 1, `${condition.minValue} <= hostLevels <= ${condition.maxValue}`);
      },
      str: function(condition) {
        return condition.minValue + '~' + condition.maxValue;
      },
      fromStr: function(str, condition) {
        var maxValue, minValue;
        [minValue, maxValue] = str.split('~');
        condition.minValue = parseInt(minValue, 10);
        condition.maxValue = parseInt(maxValue, 10);
        if (!(condition.minValue > 0)) {
          condition.minValue = 1;
        }
        if (!(condition.maxValue > 0)) {
          condition.maxValue = 1;
        }
        return condition;
      }
    },
    'WeekdayCondition': {
      abbrs: ['WD', 'Week', 'Day', 'Weekday'],
      analyze: function(condition) {
        return null;
      },
      match: function(condition, request) {
        var day;
        day = new Date().getDay();
        if (condition.days) {
          return condition.days.charCodeAt(day) > 64;
        }
        return condition.startDay <= day && day <= condition.endDay;
      },
      compile: function(condition) {
        var getDay;
        getDay = new U2.AST_Call({
          args: [],
          expression: new U2.AST_Dot({
            property: 'getDay',
            expression: new U2.AST_New({
              args: [],
              expression: new U2.AST_SymbolRef({
                name: 'Date'
              })
            })
          })
        });
        if (condition.days) {
          return new U2.AST_Binary({
            left: new U2.AST_Call({
              expression: new U2.AST_Dot({
                expression: new U2.AST_String({
                  value: condition.days
                }),
                property: 'charCodeAt'
              }),
              args: [getDay]
            }),
            operator: '>',
            right: new U2.AST_Number({
              value: 64
            })
          });
        } else {
          return this.between(getDay, condition.startDay, condition.endDay);
        }
      },
      str: function(condition) {
        if (condition.days) {
          return condition.days;
        } else {
          return condition.startDay + '~' + condition.endDay;
        }
      },
      fromStr: function(str, condition) {
        var endDay, ref, ref1, startDay;
        if (str.indexOf('~') < 0 && str.length === 7) {
          condition.days = str;
        } else {
          [startDay, endDay] = str.split('~');
          condition.startDay = parseInt(startDay, 10);
          condition.endDay = parseInt(endDay, 10);
          if (!((0 <= (ref = condition.startDay) && ref <= 6))) {
            condition.startDay = 0;
          }
          if (!((0 <= (ref1 = condition.endDay) && ref1 <= 6))) {
            condition.endDay = 0;
          }
        }
        return condition;
      }
    },
    'TimeCondition': {
      abbrs: ['T', 'Time', 'Hour'],
      analyze: function(condition) {
        return null;
      },
      match: function(condition, request) {
        var hour;
        hour = new Date().getHours();
        return condition.startHour <= hour && hour <= condition.endHour;
      },
      compile: function(condition) {
        var val;
        val = new U2.AST_Call({
          args: [],
          expression: new U2.AST_Dot({
            property: 'getHours',
            expression: new U2.AST_New({
              args: [],
              expression: new U2.AST_SymbolRef({
                name: 'Date'
              })
            })
          })
        });
        return this.between(val, condition.startHour, condition.endHour);
      },
      str: function(condition) {
        return condition.startHour + '~' + condition.endHour;
      },
      fromStr: function(str, condition) {
        var endHour, ref, ref1, startHour;
        [startHour, endHour] = str.split('~');
        condition.startHour = parseInt(startHour, 10);
        condition.endHour = parseInt(endHour, 10);
        if (!((0 <= (ref = condition.startHour) && ref < 24))) {
          condition.startHour = 0;
        }
        if (!((0 <= (ref1 = condition.endHour) && ref1 < 24))) {
          condition.endHour = 0;
        }
        return condition;
      }
    }
  }
};

// coffeelint: enable=missing_fat_arrows
