// Generated by CoffeeScript 1.12.7
var AST_Raw, AttachedCache, Conditions, Revision, RuleList, ShexpUtils, U2, exports, ref1,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

U2 = require('uglify-js');

ShexpUtils = require('./shexp_utils');

Conditions = require('./conditions');

RuleList = require('./rule_list');

ref1 = require('./utils'), AttachedCache = ref1.AttachedCache, Revision = ref1.Revision;

AST_Raw = (function(superClass) {
  extend(AST_Raw, superClass);

  function AST_Raw(raw) {
    U2.AST_SymbolRef.call(this, {
      name: raw
    });
    this.aborts = function() {
      return false;
    };
  }

  return AST_Raw;

})(U2.AST_SymbolRef);

module.exports = exports = {
  builtinProfiles: {
    '+direct': {
      name: 'direct',
      profileType: 'DirectProfile',
      color: '#aaaaaa',
      builtin: true
    },
    '+system': {
      name: 'system',
      profileType: 'SystemProfile',
      color: '#000000',
      builtin: true
    }
  },
  schemes: [
    {
      scheme: 'http',
      prop: 'proxyForHttp'
    }, {
      scheme: 'https',
      prop: 'proxyForHttps'
    }, {
      scheme: 'ftp',
      prop: 'proxyForFtp'
    }, {
      scheme: '',
      prop: 'fallbackProxy'
    }
  ],
  pacProtocols: {
    'http': 'PROXY',
    'https': 'HTTPS',
    'socks4': 'SOCKS',
    'socks5': 'SOCKS5'
  },
  formatByType: {
    'SwitchyRuleListProfile': 'Switchy',
    'AutoProxyRuleListProfile': 'AutoProxy'
  },
  ruleListFormats: ['Switchy', 'AutoProxy'],
  parseHostPort: function(str, scheme) {
    var host, port, sep;
    sep = str.lastIndexOf(':');
    if (sep < 0) {
      return;
    }
    port = parseInt(str.substr(sep + 1)) || 80;
    host = str.substr(0, sep);
    if (!host) {
      return;
    }
    return {
      scheme: scheme,
      host: host,
      port: port
    };
  },
  pacResult: function(proxy) {
    if (proxy) {
      if (proxy.scheme === 'socks5') {
        return "SOCKS5 " + proxy.host + ":" + proxy.port + "; SOCKS " + proxy.host + ":" + proxy.port;
      } else {
        return exports.pacProtocols[proxy.scheme] + " " + proxy.host + ":" + proxy.port;
      }
    } else {
      return 'DIRECT';
    }
  },
  isFileUrl: function(url) {
    return !!((url != null ? url.substr(0, 5).toUpperCase() : void 0) === 'FILE:');
  },
  nameAsKey: function(profileName) {
    if (typeof profileName !== 'string') {
      profileName = profileName.name;
    }
    return '+' + profileName;
  },
  byName: function(profileName, options) {
    var key, ref2;
    if (typeof profileName === 'string') {
      key = exports.nameAsKey(profileName);
      profileName = (ref2 = exports.builtinProfiles[key]) != null ? ref2 : options[key];
    }
    return profileName;
  },
  byKey: function(key, options) {
    var ref2;
    if (typeof key === 'string') {
      key = (ref2 = exports.builtinProfiles[key]) != null ? ref2 : options[key];
    }
    return key;
  },
  each: function(options, callback) {
    var charCodePlus, key, profile, ref2, results;
    charCodePlus = '+'.charCodeAt(0);
    for (key in options) {
      profile = options[key];
      if (key.charCodeAt(0) === charCodePlus) {
        callback(key, profile);
      }
    }
    ref2 = exports.builtinProfiles;
    results = [];
    for (key in ref2) {
      profile = ref2[key];
      if (key.charCodeAt(0) === charCodePlus) {
        results.push(callback(key, profile));
      } else {
        results.push(void 0);
      }
    }
    return results;
  },
  profileResult: function(profileName) {
    var key;
    key = exports.nameAsKey(profileName);
    if (key === '+direct') {
      key = exports.pacResult();
    }
    return new U2.AST_String({
      value: key
    });
  },
  isIncludable: function(profile) {
    var includable;
    includable = exports._handler(profile).includable;
    if (typeof includable === 'function') {
      includable = includable.call(exports, profile);
    }
    return !!includable;
  },
  isInclusive: function(profile) {
    return !!exports._handler(profile).inclusive;
  },
  updateUrl: function(profile) {
    var ref2;
    return (ref2 = exports._handler(profile).updateUrl) != null ? ref2.call(exports, profile) : void 0;
  },
  updateContentTypeHints: function(profile) {
    var ref2;
    return (ref2 = exports._handler(profile).updateContentTypeHints) != null ? ref2.call(exports, profile) : void 0;
  },
  update: function(profile, data) {
    return exports._handler(profile).update.call(exports, profile, data);
  },
  tag: function(profile) {
    return exports._profileCache.tag(profile);
  },
  create: function(profile, opt_profileType) {
    var create;
    if (typeof profile === 'string') {
      profile = {
        name: profile,
        profileType: opt_profileType
      };
    } else if (opt_profileType) {
      profile.profileType = opt_profileType;
    }
    create = exports._handler(profile).create;
    if (!create) {
      return profile;
    }
    create.call(exports, profile);
    return profile;
  },
  updateRevision: function(profile, revision) {
    if (revision == null) {
      revision = Revision.fromTime();
    }
    return profile.revision = revision;
  },
  replaceRef: function(profile, fromName, toName) {
    var handler;
    if (!exports.isInclusive(profile)) {
      return false;
    }
    handler = exports._handler(profile);
    return handler.replaceRef.call(exports, profile, fromName, toName);
  },
  analyze: function(profile) {
    var analyze, cache, result;
    cache = exports._profileCache.get(profile, {});
    if (!Object.prototype.hasOwnProperty.call(cache, 'analyzed')) {
      analyze = exports._handler(profile).analyze;
      result = analyze != null ? analyze.call(exports, profile) : void 0;
      cache.analyzed = result;
    }
    return cache;
  },
  dropCache: function(profile) {
    return exports._profileCache.drop(profile);
  },
  directReferenceSet: function(profile) {
    var cache, handler;
    if (!exports.isInclusive(profile)) {
      return {};
    }
    cache = exports._profileCache.get(profile, {});
    if (cache.directReferenceSet) {
      return cache.directReferenceSet;
    }
    handler = exports._handler(profile);
    return cache.directReferenceSet = handler.directReferenceSet.call(exports, profile);
  },
  profileNotFound: function(name, action) {
    if (action == null) {
      throw new Error("Profile " + name + " does not exist!");
    }
    if (typeof action === 'function') {
      action = action(name);
    }
    if (typeof action === 'object' && action.profileType) {
      return action;
    }
    switch (action) {
      case 'ignore':
        return null;
      case 'dumb':
        return exports.create({
          name: name,
          profileType: 'VirtualProfile',
          defaultProfileName: 'direct'
        });
    }
    throw action;
  },
  allReferenceSet: function(profile, options, opt_args) {
    var has_out, key, name, o_profile, ref2, result;
    o_profile = profile;
    profile = exports.byName(profile, options);
    if (profile == null) {
      profile = typeof exports.profileNotFound === "function" ? exports.profileNotFound(o_profile, opt_args.profileNotFound) : void 0;
    }
    if (opt_args == null) {
      opt_args = {};
    }
    has_out = opt_args.out != null;
    result = opt_args.out != null ? opt_args.out : opt_args.out = {};
    if (profile) {
      result[exports.nameAsKey(profile.name)] = profile.name;
      ref2 = exports.directReferenceSet(profile);
      for (key in ref2) {
        name = ref2[key];
        exports.allReferenceSet(name, options, opt_args);
      }
    }
    if (!has_out) {
      delete opt_args.out;
    }
    return result;
  },
  referencedBySet: function(profile, options, opt_args) {
    var has_out, profileKey, result;
    profileKey = exports.nameAsKey(profile);
    if (opt_args == null) {
      opt_args = {};
    }
    has_out = opt_args.out != null;
    result = opt_args.out != null ? opt_args.out : opt_args.out = {};
    exports.each(options, function(key, prof) {
      if (exports.directReferenceSet(prof)[profileKey]) {
        result[key] = prof.name;
        return exports.referencedBySet(prof, options, opt_args);
      }
    });
    if (!has_out) {
      delete opt_args.out;
    }
    return result;
  },
  validResultProfilesFor: function(profile, options) {
    var profileKey, ref, result;
    profile = exports.byName(profile, options);
    if (!exports.isInclusive(profile)) {
      return [];
    }
    profileKey = exports.nameAsKey(profile);
    ref = exports.referencedBySet(profile, options);
    ref[profileKey] = profileKey;
    result = [];
    exports.each(options, function(key, prof) {
      if (!ref[key] && exports.isIncludable(prof)) {
        return result.push(prof);
      }
    });
    return result;
  },
  match: function(profile, request, opt_profileType) {
    var cache, match;
    if (opt_profileType == null) {
      opt_profileType = profile.profileType;
    }
    cache = exports.analyze(profile);
    match = exports._handler(opt_profileType).match;
    return match != null ? match.call(exports, profile, request, cache) : void 0;
  },
  compile: function(profile, opt_profileType) {
    var cache, handler;
    if (opt_profileType == null) {
      opt_profileType = profile.profileType;
    }
    cache = exports.analyze(profile);
    if (cache.compiled) {
      return cache.compiled;
    }
    handler = exports._handler(opt_profileType);
    return cache.compiled = handler.compile.call(exports, profile, cache);
  },
  _profileCache: new AttachedCache(function(profile) {
    return profile.revision;
  }),
  _handler: function(profileType) {
    var handler;
    if (typeof profileType !== 'string') {
      profileType = profileType.profileType;
    }
    handler = profileType;
    while (typeof handler === 'string') {
      handler = exports._profileTypes[handler];
    }
    if (handler == null) {
      throw new Error("Unknown profile type: " + profileType);
    }
    return handler;
  },
  _profileTypes: {
    'SystemProfile': {
      compile: function(profile) {
        throw new Error("SystemProfile cannot be used in PAC scripts");
      }
    },
    'DirectProfile': {
      includable: true,
      compile: function(profile) {
        return new U2.AST_String({
          value: this.pacResult()
        });
      }
    },
    'FixedProfile': {
      includable: true,
      create: function(profile) {
        return profile.bypassList != null ? profile.bypassList : profile.bypassList = [
          {
            conditionType: 'BypassCondition',
            pattern: '127.0.0.1'
          }, {
            conditionType: 'BypassCondition',
            pattern: '[::1]'
          }, {
            conditionType: 'BypassCondition',
            pattern: 'localhost'
          }
        ];
      },
      match: function(profile, request) {
        var cond, i, j, len, len1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, s;
        if (profile.bypassList) {
          ref2 = profile.bypassList;
          for (i = 0, len = ref2.length; i < len; i++) {
            cond = ref2[i];
            if (Conditions.match(cond, request)) {
              return [
                this.pacResult(), cond, {
                  scheme: 'direct'
                }, void 0
              ];
            }
          }
        }
        ref3 = this.schemes;
        for (j = 0, len1 = ref3.length; j < len1; j++) {
          s = ref3[j];
          if (s.scheme === request.scheme && profile[s.prop]) {
            return [this.pacResult(profile[s.prop]), s.scheme, profile[s.prop], (ref4 = (ref5 = profile.auth) != null ? ref5[s.prop] : void 0) != null ? ref4 : (ref6 = profile.auth) != null ? ref6['all'] : void 0];
          }
        }
        return [this.pacResult(profile.fallbackProxy), '', profile.fallbackProxy, (ref7 = (ref8 = profile.auth) != null ? ref8.fallbackProxy : void 0) != null ? ref7 : (ref9 = profile.auth) != null ? ref9['all'] : void 0];
      },
      compile: function(profile) {
        var body, cond, condition, conditions, i, len, ref2, ret, s;
        if ((!profile.bypassList || !profile.fallbackProxy) && !profile.proxyForHttp && !profile.proxyForHttps && !profile.proxyForFtp) {
          return new U2.AST_String({
            value: this.pacResult(profile.fallbackProxy)
          });
        }
        body = [
          new U2.AST_Directive({
            value: 'use strict'
          })
        ];
        if (profile.bypassList && profile.bypassList.length) {
          conditions = null;
          ref2 = profile.bypassList;
          for (i = 0, len = ref2.length; i < len; i++) {
            cond = ref2[i];
            condition = Conditions.compile(cond);
            if (conditions != null) {
              conditions = new U2.AST_Binary({
                left: conditions,
                operator: '||',
                right: condition
              });
            } else {
              conditions = condition;
            }
          }
          body.push(new U2.AST_If({
            condition: conditions,
            body: new U2.AST_Return({
              value: new U2.AST_String({
                value: this.pacResult()
              })
            })
          }));
        }
        if (!profile.proxyForHttp && !profile.proxyForHttps && !profile.proxyForFtp) {
          body.push(new U2.AST_Return({
            value: new U2.AST_String({
              value: this.pacResult(profile.fallbackProxy)
            })
          }));
        } else {
          body.push(new U2.AST_Switch({
            expression: new U2.AST_SymbolRef({
              name: 'scheme'
            }),
            body: (function() {
              var j, len1, ref3, results;
              ref3 = this.schemes;
              results = [];
              for (j = 0, len1 = ref3.length; j < len1; j++) {
                s = ref3[j];
                if (!(!s.scheme || profile[s.prop])) {
                  continue;
                }
                ret = [
                  new U2.AST_Return({
                    value: new U2.AST_String({
                      value: this.pacResult(profile[s.prop])
                    })
                  })
                ];
                if (s.scheme) {
                  results.push(new U2.AST_Case({
                    expression: new U2.AST_String({
                      value: s.scheme
                    }),
                    body: ret
                  }));
                } else {
                  results.push(new U2.AST_Default({
                    body: ret
                  }));
                }
              }
              return results;
            }).call(this)
          }));
        }
        return new U2.AST_Function({
          argnames: [
            new U2.AST_SymbolFunarg({
              name: 'url'
            }), new U2.AST_SymbolFunarg({
              name: 'host'
            }), new U2.AST_SymbolFunarg({
              name: 'scheme'
            })
          ],
          body: body
        });
      }
    },
    'PacProfile': {
      includable: function(profile) {
        return !this.isFileUrl(profile.pacUrl);
      },
      create: function(profile) {
        return profile.pacScript != null ? profile.pacScript : profile.pacScript = 'function FindProxyForURL(url, host) {\n  return "DIRECT";\n}';
      },
      compile: function(profile) {
        return new U2.AST_Call({
          args: [new U2.AST_This],
          expression: new U2.AST_Dot({
            property: 'call',
            expression: new U2.AST_Function({
              argnames: [],
              body: [
                new AST_Raw(';\n' + profile.pacScript + '\n\n/* End of PAC */;'), new U2.AST_Return({
                  value: new U2.AST_SymbolRef({
                    name: 'FindProxyForURL'
                  })
                })
              ]
            })
          })
        });
      },
      updateUrl: function(profile) {
        if (this.isFileUrl(profile.pacUrl)) {
          return void 0;
        } else {
          return profile.pacUrl;
        }
      },
      updateContentTypeHints: function() {
        return ['!text/html', '!application/xhtml+xml', 'application/x-ns-proxy-autoconfig', 'application/x-javascript-config'];
      },
      update: function(profile, data) {
        if (profile.pacScript === data) {
          return false;
        }
        profile.pacScript = data;
        return true;
      }
    },
    'AutoDetectProfile': 'PacProfile',
    'SwitchProfile': {
      includable: true,
      inclusive: true,
      create: function(profile) {
        if (profile.defaultProfileName == null) {
          profile.defaultProfileName = 'direct';
        }
        return profile.rules != null ? profile.rules : profile.rules = [];
      },
      directReferenceSet: function(profile) {
        var i, len, ref2, refs, rule;
        refs = {};
        refs[exports.nameAsKey(profile.defaultProfileName)] = profile.defaultProfileName;
        ref2 = profile.rules;
        for (i = 0, len = ref2.length; i < len; i++) {
          rule = ref2[i];
          refs[exports.nameAsKey(rule.profileName)] = rule.profileName;
        }
        return refs;
      },
      analyze: function(profile) {
        return profile.rules;
      },
      replaceRef: function(profile, fromName, toName) {
        var changed, i, len, ref2, rule;
        changed = false;
        if (profile.defaultProfileName === fromName) {
          profile.defaultProfileName = toName;
          changed = true;
        }
        ref2 = profile.rules;
        for (i = 0, len = ref2.length; i < len; i++) {
          rule = ref2[i];
          if (rule.profileName === fromName) {
            rule.profileName = toName;
            changed = true;
          }
        }
        return changed;
      },
      match: function(profile, request, cache) {
        var i, len, ref2, rule;
        ref2 = cache.analyzed;
        for (i = 0, len = ref2.length; i < len; i++) {
          rule = ref2[i];
          if (Conditions.match(rule.condition, request)) {
            return rule;
          }
        }
        return [exports.nameAsKey(profile.defaultProfileName), null];
      },
      compile: function(profile, cache) {
        var body, i, len, rule, rules;
        rules = cache.analyzed;
        if (rules.length === 0) {
          return this.profileResult(profile.defaultProfileName);
        }
        body = [
          new U2.AST_Directive({
            value: 'use strict'
          })
        ];
        for (i = 0, len = rules.length; i < len; i++) {
          rule = rules[i];
          body.push(new U2.AST_If({
            condition: Conditions.compile(rule.condition),
            body: new U2.AST_Return({
              value: this.profileResult(rule.profileName)
            })
          }));
        }
        body.push(new U2.AST_Return({
          value: this.profileResult(profile.defaultProfileName)
        }));
        return new U2.AST_Function({
          argnames: [
            new U2.AST_SymbolFunarg({
              name: 'url'
            }), new U2.AST_SymbolFunarg({
              name: 'host'
            }), new U2.AST_SymbolFunarg({
              name: 'scheme'
            })
          ],
          body: body
        });
      }
    },
    'VirtualProfile': 'SwitchProfile',
    'RuleListProfile': {
      includable: true,
      inclusive: true,
      create: function(profile) {
        var ref2;
        if (profile.profileType == null) {
          profile.profileType = 'RuleListProfile';
        }
        if (profile.format == null) {
          profile.format = (ref2 = exports.formatByType[profile.profileType]) != null ? ref2 : 'Switchy';
        }
        if (profile.defaultProfileName == null) {
          profile.defaultProfileName = 'direct';
        }
        if (profile.matchProfileName == null) {
          profile.matchProfileName = 'direct';
        }
        return profile.ruleList != null ? profile.ruleList : profile.ruleList = '';
      },
      directReferenceSet: function(profile) {
        var i, len, name, ref2, ref3, refs;
        if (profile.ruleList != null) {
          refs = (ref2 = RuleList[profile.format]) != null ? typeof ref2.directReferenceSet === "function" ? ref2.directReferenceSet(profile) : void 0 : void 0;
          if (refs) {
            return refs;
          }
        }
        refs = {};
        ref3 = [profile.matchProfileName, profile.defaultProfileName];
        for (i = 0, len = ref3.length; i < len; i++) {
          name = ref3[i];
          refs[exports.nameAsKey(name)] = name;
        }
        return refs;
      },
      replaceRef: function(profile, fromName, toName) {
        var changed;
        changed = false;
        if (profile.defaultProfileName === fromName) {
          profile.defaultProfileName = toName;
          changed = true;
        }
        if (profile.matchProfileName === fromName) {
          profile.matchProfileName = toName;
          changed = true;
        }
        return changed;
      },
      analyze: function(profile) {
        var format, formatHandler, ref2, ref3, ruleList;
        format = (ref2 = profile.format) != null ? ref2 : exports.formatByType[profile.profileType];
        formatHandler = RuleList[format];
        if (!formatHandler) {
          throw new Error("Unsupported rule list format " + format + "!");
        }
        ruleList = ((ref3 = profile.ruleList) != null ? ref3.trim() : void 0) || '';
        if (formatHandler.preprocess != null) {
          ruleList = formatHandler.preprocess(ruleList);
        }
        return formatHandler.parse(ruleList, profile.matchProfileName, profile.defaultProfileName);
      },
      match: function(profile, request) {
        var result;
        return result = exports.match(profile, request, 'SwitchProfile');
      },
      compile: function(profile) {
        return exports.compile(profile, 'SwitchProfile');
      },
      updateUrl: function(profile) {
        return profile.sourceUrl;
      },
      updateContentTypeHints: function() {
        return ['!text/html', '!application/xhtml+xml', 'text/plain', '*'];
      },
      update: function(profile, data) {
        var base, base1, format, formatHandler, formatName, original, ref2, result;
        data = data.trim();
        original = (ref2 = profile.format) != null ? ref2 : exports.formatByType[profile.profileType];
        profile.profileType = 'RuleListProfile';
        format = original;
        if ((typeof (base = RuleList[format]).detect === "function" ? base.detect(data) : void 0) === false) {
          format = null;
        }
        for (formatName in RuleList) {
          if (!hasProp.call(RuleList, formatName)) continue;
          result = typeof (base1 = RuleList[formatName]).detect === "function" ? base1.detect(data) : void 0;
          if (result === true || (result !== false && (format == null))) {
            profile.format = format = formatName;
          }
        }
        if (format == null) {
          format = original;
        }
        formatHandler = RuleList[format];
        if (formatHandler.preprocess != null) {
          data = formatHandler.preprocess(data);
        }
        if (profile.ruleList === data) {
          return false;
        }
        profile.ruleList = data;
        return true;
      }
    },
    'SwitchyRuleListProfile': 'RuleListProfile',
    'AutoProxyRuleListProfile': 'RuleListProfile'
  }
};
