// Generated by CoffeeScript 1.12.7
var Buffer, Conditions, exports, strStartsWith,
  hasProp = {}.hasOwnProperty;

Buffer = require('buffer').Buffer;

Conditions = require('./conditions');

strStartsWith = function(str, prefix) {
  return str.substr(0, prefix.length) === prefix;
};

module.exports = exports = {
  'AutoProxy': {
    magicPrefix: 'W0F1dG9Qcm94',
    detect: function(text) {
      if (strStartsWith(text, exports['AutoProxy'].magicPrefix)) {
        return true;
      } else if (strStartsWith(text, '[AutoProxy')) {
        return true;
      }
    },
    preprocess: function(text) {
      if (strStartsWith(text, exports['AutoProxy'].magicPrefix)) {
        text = new Buffer(text, 'base64').toString('utf8');
      }
      return text;
    },
    parse: function(text, matchProfileName, defaultProfileName) {
      var cond, exclusive_rules, i, len, line, list, normal_rules, profile, ref, source;
      normal_rules = [];
      exclusive_rules = [];
      ref = text.split(/\n|\r/);
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        line = line.trim();
        if (line.length === 0 || line[0] === '!' || line[0] === '[') {
          continue;
        }
        source = line;
        profile = matchProfileName;
        list = normal_rules;
        if (line[0] === '@' && line[1] === '@') {
          profile = defaultProfileName;
          list = exclusive_rules;
          line = line.substring(2);
        }
        cond = line[0] === '/' ? {
          conditionType: 'UrlRegexCondition',
          pattern: line.substring(1, line.length - 1)
        } : line[0] === '|' ? line[1] === '|' ? {
          conditionType: 'HostWildcardCondition',
          pattern: "*." + line.substring(2)
        } : {
          conditionType: 'UrlWildcardCondition',
          pattern: line.substring(1) + "*"
        } : line.indexOf('*') < 0 ? {
          conditionType: 'KeywordCondition',
          pattern: line
        } : {
          conditionType: 'UrlWildcardCondition',
          pattern: 'http://*' + line + '*'
        };
        list.push({
          condition: cond,
          profileName: profile,
          source: source
        });
      }
      return exclusive_rules.concat(normal_rules);
    }
  },
  'Switchy': {
    omegaPrefix: '[SwitchyOmega Conditions',
    specialLineStart: "[;#@!",
    detect: function(text) {
      if (strStartsWith(text, exports['Switchy'].omegaPrefix)) {
        return true;
      }
    },
    parse: function(text, matchProfileName, defaultProfileName) {
      var parser, switchy;
      switchy = exports['Switchy'];
      parser = switchy.getParser(text);
      return switchy[parser](text, matchProfileName, defaultProfileName);
    },
    directReferenceSet: function(arg) {
      var defaultProfileName, i, iSpace, len, line, matchProfileName, parser, profile, ref, refs, ruleList, switchy, text;
      ruleList = arg.ruleList, matchProfileName = arg.matchProfileName, defaultProfileName = arg.defaultProfileName;
      text = ruleList.trim();
      switchy = exports['Switchy'];
      parser = switchy.getParser(text);
      if (parser !== 'parseOmega') {
        return;
      }
      if (!/(^|\n)@with\s+results?(\r|\n|$)/i.test(text)) {
        return;
      }
      refs = {};
      ref = text.split(/\n|\r/);
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        line = line.trim();
        if (switchy.specialLineStart.indexOf(line[0]) < 0) {
          iSpace = line.lastIndexOf(' +');
          if (iSpace < 0) {
            profile = defaultProfileName || 'direct';
          } else {
            profile = line.substr(iSpace + 2).trim();
          }
          refs['+' + profile] = profile;
        }
      }
      return refs;
    },
    compose: function(arg, arg1) {
      var defaultProfileName, eol, i, len, line, ref, rule, ruleList, rules, specialLineStart, useExclusive, withResult;
      rules = arg.rules, defaultProfileName = arg.defaultProfileName;
      ref = arg1 != null ? arg1 : {}, withResult = ref.withResult, useExclusive = ref.useExclusive;
      eol = '\r\n';
      ruleList = '[SwitchyOmega Conditions]' + eol;
      if (useExclusive == null) {
        useExclusive = !withResult;
      }
      if (withResult) {
        ruleList += '@with result' + eol + eol;
      } else {
        ruleList += eol;
      }
      specialLineStart = exports['Switchy'].specialLineStart + '+';
      for (i = 0, len = rules.length; i < len; i++) {
        rule = rules[i];
        if (rule.note) {
          ruleList += '@note ' + rule.note + eol;
        }
        line = Conditions.str(rule.condition);
        if (useExclusive && rule.profileName === defaultProfileName) {
          line = '!' + line;
        } else {
          if (specialLineStart.indexOf(line[0]) >= 0) {
            line = ': ' + line;
          }
          if (withResult) {
            line += ' +' + rule.profileName;
          }
        }
        ruleList += line + eol;
      }
      if (withResult) {
        ruleList += eol + '* +' + defaultProfileName + eol;
      }
      return ruleList;
    },
    getParser: function(text) {
      var parser, switchy;
      switchy = exports['Switchy'];
      parser = 'parseOmega';
      if (!strStartsWith(text, switchy.omegaPrefix)) {
        if (text[0] === '#' || text.indexOf('\n#') >= 0) {
          parser = 'parseLegacy';
        }
      }
      return parser;
    },
    conditionFromLegacyWildcard: function(pattern) {
      var host;
      if (pattern[0] === '@') {
        pattern = pattern.substring(1);
      } else {
        if (pattern.indexOf('://') <= 0 && pattern[0] !== '*') {
          pattern = '*' + pattern;
        }
        if (pattern[pattern.length - 1] !== '*') {
          pattern += '*';
        }
      }
      host = Conditions.urlWildcard2HostWildcard(pattern);
      if (host) {
        return {
          conditionType: 'HostWildcardCondition',
          pattern: host
        };
      } else {
        return {
          conditionType: 'UrlWildcardCondition',
          pattern: pattern
        };
      }
    },
    parseLegacy: function(text, matchProfileName, defaultProfileName) {
      var begin, cond, exclusive_rules, i, len, line, list, normal_rules, profile, ref, section, source;
      normal_rules = [];
      exclusive_rules = [];
      begin = false;
      section = 'WILDCARD';
      ref = text.split(/\n|\r/);
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        line = line.trim();
        if (line.length === 0 || line[0] === ';') {
          continue;
        }
        if (!begin) {
          if (line.toUpperCase() === '#BEGIN') {
            begin = true;
          }
          continue;
        }
        if (line.toUpperCase() === '#END') {
          break;
        }
        if (line[0] === '[' && line[line.length - 1] === ']') {
          section = line.substring(1, line.length - 1).toUpperCase();
          continue;
        }
        source = line;
        profile = matchProfileName;
        list = normal_rules;
        if (line[0] === '!') {
          profile = defaultProfileName;
          list = exclusive_rules;
          line = line.substring(1);
        }
        cond = (function() {
          switch (section) {
            case 'WILDCARD':
              return exports['Switchy'].conditionFromLegacyWildcard(line);
            case 'REGEXP':
              return {
                conditionType: 'UrlRegexCondition',
                pattern: line
              };
            default:
              return null;
          }
        })();
        if (cond != null) {
          list.push({
            condition: cond,
            profileName: profile,
            source: source
          });
        }
      }
      return exclusive_rules.concat(normal_rules);
    },
    parseOmega: function(text, matchProfileName, defaultProfileName, args) {
      var cond, directive, error, exclusiveProfile, feature, i, iSpace, includeSource, j, len, len1, line, lno, noteForNextRule, profile, ref, ref1, rule, rules, rulesWithDefaultProfile, source, strict, withResult;
      if (args == null) {
        args = {};
      }
      strict = args.strict;
      if (strict) {
        error = function(fields) {
          var err, key, value;
          err = new Error(fields.message);
          for (key in fields) {
            if (!hasProp.call(fields, key)) continue;
            value = fields[key];
            err[key] = value;
          }
          throw err;
        };
      }
      includeSource = (ref = args.source) != null ? ref : true;
      rules = [];
      rulesWithDefaultProfile = [];
      withResult = false;
      exclusiveProfile = null;
      noteForNextRule = null;
      lno = 0;
      ref1 = text.split(/\n|\r/);
      for (i = 0, len = ref1.length; i < len; i++) {
        line = ref1[i];
        lno++;
        line = line.trim();
        if (line.length === 0) {
          continue;
        }
        switch (line[0]) {
          case '[':
            continue;
          case ';':
            continue;
          case '@':
            iSpace = line.indexOf(' ');
            if (iSpace < 0) {
              iSpace = line.length;
            }
            directive = line.substr(1, iSpace - 1);
            line = line.substr(iSpace + 1).trim();
            switch (directive.toUpperCase()) {
              case 'WITH':
                feature = line.toUpperCase();
                if (feature === 'RESULT' || feature === 'RESULTS') {
                  withResult = true;
                }
                break;
              case 'NOTE':
                noteForNextRule = line;
            }
            continue;
        }
        source = null;
        if (strict) {
          exclusiveProfile = null;
        }
        if (line[0] === '!') {
          profile = withResult ? null : defaultProfileName;
          source = line;
          line = line.substr(1);
        } else if (withResult) {
          iSpace = line.lastIndexOf(' +');
          if (iSpace < 0) {
            if (typeof error === "function") {
              error({
                message: "Missing result profile name: " + line,
                reason: 'missingResultProfile',
                source: line,
                sourceLineNo: lno
              });
            }
            continue;
          }
          profile = line.substr(iSpace + 2).trim();
          line = line.substr(0, iSpace).trim();
          if (line === '*') {
            exclusiveProfile = profile;
          }
        } else {
          profile = matchProfileName;
        }
        cond = Conditions.fromStr(line);
        if (!cond) {
          if (typeof error === "function") {
            error({
              message: "Invalid rule: " + line,
              reason: 'invalidRule',
              source: source != null ? source : line,
              sourceLineNo: lno
            });
          }
          continue;
        }
        rule = {
          condition: cond,
          profileName: profile,
          source: includeSource ? source != null ? source : line : void 0
        };
        if (noteForNextRule != null) {
          rule.note = noteForNextRule;
          noteForNextRule = null;
        }
        rules.push(rule);
        if (!profile) {
          rulesWithDefaultProfile.push(rule);
        }
      }
      if (withResult) {
        if (!exclusiveProfile) {
          if (strict) {
            if (typeof error === "function") {
              error({
                message: "Missing default rule with catch-all '*' condition",
                reason: 'noDefaultRule'
              });
            }
          }
          exclusiveProfile = defaultProfileName || 'direct';
        }
        for (j = 0, len1 = rulesWithDefaultProfile.length; j < len1; j++) {
          rule = rulesWithDefaultProfile[j];
          rule.profileName = exclusiveProfile;
        }
      }
      return rules;
    }
  }
};
