// Generated by CoffeeScript 1.12.7
var exports;

module.exports = exports = {
  regExpMetaChars: (function() {
    var chars, i, j, ref, set;
    chars = '\\[\^$.|?*+(){}/';
    set = {};
    for (i = j = 0, ref = chars.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      set[chars.charCodeAt(i)] = true;
    }
    return set;
  })(),
  escapeSlash: function(pattern) {
    var charCodeBackSlash, charCodeSlash, code, escaped, i, j, ref, result, start;
    charCodeSlash = 47;
    charCodeBackSlash = 92;
    escaped = false;
    start = 0;
    result = '';
    for (i = j = 0, ref = pattern.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      code = pattern.charCodeAt(i);
      if (code === charCodeSlash && !escaped) {
        result += pattern.substring(start, i);
        result += '\\';
        start = i;
      }
      escaped = code === charCodeBackSlash && !escaped;
    }
    return result += pattern.substr(start);
  },
  shExp2RegExp: function(pattern, options) {
    var charCodeAsterisk, charCodeQuestion, code, end, i, j, ref, ref1, regex, start, trimAsterisk;
    trimAsterisk = (options != null ? options.trimAsterisk : void 0) || false;
    start = 0;
    end = pattern.length;
    charCodeAsterisk = 42;
    charCodeQuestion = 63;
    if (trimAsterisk) {
      while (start < end && pattern.charCodeAt(start) === charCodeAsterisk) {
        start++;
      }
      while (start < end && pattern.charCodeAt(end - 1) === charCodeAsterisk) {
        end--;
      }
      if (end - start === 1 && pattern.charCodeAt(start) === charCodeAsterisk) {
        return '';
      }
    }
    regex = '';
    if (start === 0) {
      regex += '^';
    }
    for (i = j = ref = start, ref1 = end; ref <= ref1 ? j < ref1 : j > ref1; i = ref <= ref1 ? ++j : --j) {
      code = pattern.charCodeAt(i);
      switch (code) {
        case charCodeAsterisk:
          regex += '.*';
          break;
        case charCodeQuestion:
          regex += '.';
          break;
        default:
          if (exports.regExpMetaChars[code] >= 0) {
            regex += '\\';
          }
          regex += pattern[i];
      }
    }
    if (end === pattern.length) {
      regex += '$';
    }
    return regex;
  }
};
