// Generated by CoffeeScript 1.12.7
var AttachedCache, Revision, Url, tld;

Revision = {
  fromTime: function(time) {
    time = time ? new Date(time) : new Date();
    return time.getTime().toString(16);
  },
  compare: function(a, b) {
    if (!a && !b) {
      return 0;
    }
    if (!a) {
      return -1;
    }
    if (!b) {
      return 1;
    }
    if (a.length > b.length) {
      return 1;
    }
    if (a.length < b.length) {
      return -1;
    }
    if (a > b) {
      return 1;
    }
    if (a < b) {
      return -1;
    }
    return 0;
  }
};

exports.Revision = Revision;

AttachedCache = (function() {
  function AttachedCache(opt_prop, tag1) {
    this.tag = tag1;
    this.prop = opt_prop;
    if (typeof this.tag === 'undefined') {
      this.tag = opt_prop;
      this.prop = '_cache';
    }
  }

  AttachedCache.prototype.get = function(obj, otherwise) {
    var cache, tag, value;
    tag = this.tag(obj);
    cache = this._getCache(obj);
    if ((cache != null) && cache.tag === tag) {
      return cache.value;
    }
    value = typeof otherwise === 'function' ? otherwise() : otherwise;
    this._setCache(obj, {
      tag: tag,
      value: value
    });
    return value;
  };

  AttachedCache.prototype.drop = function(obj) {
    if (obj[this.prop] != null) {
      return obj[this.prop] = void 0;
    }
  };

  AttachedCache.prototype._getCache = function(obj) {
    return obj[this.prop];
  };

  AttachedCache.prototype._setCache = function(obj, value) {
    if (!Object.prototype.hasOwnProperty.call(obj, this.prop)) {
      Object.defineProperty(obj, this.prop, {
        writable: true
      });
    }
    return obj[this.prop] = value;
  };

  return AttachedCache;

})();

exports.AttachedCache = AttachedCache;

tld = require('tldjs');

exports.isIp = function(domain) {
  var lastCharCode;
  if (domain.indexOf(':') > 0) {
    return true;
  }
  lastCharCode = domain.charCodeAt(domain.length - 1);
  if ((48 <= lastCharCode && lastCharCode <= 57)) {
    return true;
  }
  return false;
};

exports.getBaseDomain = function(domain) {
  var ref;
  if (exports.isIp(domain)) {
    return domain;
  }
  return (ref = tld.getDomain(domain)) != null ? ref : domain;
};

exports.wildcardForDomain = function(domain) {
  if (exports.isIp(domain)) {
    return domain;
  }
  return '*.' + exports.getBaseDomain(domain);
};

Url = require('url');

exports.wildcardForUrl = function(url) {
  var domain;
  domain = Url.parse(url).hostname;
  return exports.wildcardForDomain(domain);
};
